"""unicidade de conta bancaria por cliente

Revision ID: 275d8afe1f7f
Revises: c258a15af342
Create Date: 2026-09-12 02:00:27.967594

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '275d8afe1f7f'
down_revision: Union[str, Sequence[str], None] = 'c258a15af342'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("bank_accounts") as batch_op:
        batch_op.create_unique_constraint(
            "uq_bank_account_per_client", ["client_id", "bank", "account_number"]
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("bank_accounts") as batch_op:
        batch_op.drop_constraint("uq_bank_account_per_client", type_="unique")
    # ### end Alembic commands ###
