"""pedidos notas fiscais FTP021A1 para representante

Revision ID: 4d630a2d3f70
Revises: 87468562dd16
Create Date: 2026-09-12 22:52:12.163789

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d630a2d3f70'
down_revision: Union[str, Sequence[str], None] = '87468562dd16'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pedidos_notas_fiscais',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('import_file_id', sa.Uuid(), nullable=False),
    sa.Column('bank_account_id', sa.Uuid(), nullable=False),
    sa.Column('local', sa.String(length=100), nullable=False),
    sa.Column('pedido', sa.String(length=30), nullable=True),
    sa.Column('nota_fiscal', sa.String(length=30), nullable=False),
    sa.Column('serie', sa.String(length=10), nullable=True),
    sa.Column('data_emissao', sa.Date(), nullable=True),
    sa.Column('cliente_id', sa.String(length=30), nullable=True),
    sa.Column('razao_social', sa.String(length=255), nullable=True),
    sa.Column('representante_id', sa.String(length=30), nullable=True),
    sa.Column('representante_nome', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['bank_account_id'], ['bank_accounts.id'], ),
    sa.ForeignKeyConstraint(['import_file_id'], ['import_files.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_pedido_nf_matching', 'pedidos_notas_fiscais', ['nota_fiscal', 'bank_account_id'], unique=False)
    op.create_index(op.f('ix_pedidos_notas_fiscais_nota_fiscal'), 'pedidos_notas_fiscais', ['nota_fiscal'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pedidos_notas_fiscais_nota_fiscal'), table_name='pedidos_notas_fiscais')
    op.drop_index('ix_pedido_nf_matching', table_name='pedidos_notas_fiscais')
    op.drop_table('pedidos_notas_fiscais')
    # ### end Alembic commands ###
