"""documentos recebidos CRP032A1 e fonte opcional na conciliacao

Revision ID: 6b34f48a4afe
Revises: 275d8afe1f7f
Create Date: 2026-09-12 14:52:46.338202

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b34f48a4afe'
down_revision: Union[str, Sequence[str], None] = '275d8afe1f7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documentos_recebidos',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('import_file_id', sa.Uuid(), nullable=False),
    sa.Column('bank_account_id', sa.Uuid(), nullable=False),
    sa.Column('documento', sa.String(length=50), nullable=False),
    sa.Column('normalized_title', sa.String(length=50), nullable=True),
    sa.Column('cliente', sa.String(length=255), nullable=True),
    sa.Column('data_pagamento', sa.Date(), nullable=True),
    sa.Column('valor_emissao', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('impostos_retidos', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('valor_desconto', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('valor_abatimento', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('valor_juros', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('valor_multa', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('valor_pago', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('raw_data', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['bank_account_id'], ['bank_accounts.id'], ),
    sa.ForeignKeyConstraint(['import_file_id'], ['import_files.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_documento_recebido_matching', 'documentos_recebidos', ['normalized_title', 'bank_account_id'], unique=False)
    op.create_index(op.f('ix_documentos_recebidos_normalized_title'), 'documentos_recebidos', ['normalized_title'], unique=False)

    # 'kind' deixa de ser um Enum de banco e vira texto simples (mais largo,
    # 20 chars) — ver comentário no modelo ImportFile: evita precisar de
    # ALTER TYPE toda vez que um novo tipo de arquivo aparecer. batch_alter_table
    # garante que isso funcione tanto em SQLite (recria a tabela) quanto em
    # Postgres (ALTER COLUMN direto).
    with op.batch_alter_table('import_files') as batch_op:
        batch_op.alter_column(
            'kind', existing_type=sa.VARCHAR(length=4), type_=sa.String(length=20), existing_nullable=False,
        )

    op.add_column('reconciliations', sa.Column('crp032a1_import_file_id', sa.Uuid(), nullable=True))
    with op.batch_alter_table('reconciliations') as batch_op:
        batch_op.create_foreign_key(
            'fk_reconciliations_crp032a1_import_file_id', 'import_files', ['crp032a1_import_file_id'], ['id'],
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reconciliations') as batch_op:
        batch_op.drop_constraint('fk_reconciliations_crp032a1_import_file_id', type_='foreignkey')
    op.drop_column('reconciliations', 'crp032a1_import_file_id')
    with op.batch_alter_table('import_files') as batch_op:
        batch_op.alter_column(
            'kind', existing_type=sa.String(length=20), type_=sa.VARCHAR(length=4), existing_nullable=False,
        )
    op.drop_index(op.f('ix_documentos_recebidos_normalized_title'), table_name='documentos_recebidos')
    op.drop_index('ix_documento_recebido_matching', table_name='documentos_recebidos')
    op.drop_table('documentos_recebidos')
    # ### end Alembic commands ###
