"""notas fiscais emitidas FTP050 e vencimento agencia no banco

Revision ID: 87468562dd16
Revises: a3899b42f342
Create Date: 2026-09-12 20:03:13.427154

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87468562dd16'
down_revision: Union[str, Sequence[str], None] = 'a3899b42f342'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notas_fiscais_emitidas',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('import_file_id', sa.Uuid(), nullable=False),
    sa.Column('bank_account_id', sa.Uuid(), nullable=False),
    sa.Column('local_nome', sa.String(length=100), nullable=False),
    sa.Column('local_id', sa.Integer(), nullable=True),
    sa.Column('data_emissao', sa.Date(), nullable=True),
    sa.Column('nota_fiscal', sa.String(length=30), nullable=False),
    sa.Column('cliente_id', sa.String(length=30), nullable=True),
    sa.Column('razao_social', sa.String(length=255), nullable=True),
    sa.Column('cnpj_cpf', sa.String(length=20), nullable=True),
    sa.Column('total', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['bank_account_id'], ['bank_accounts.id'], ),
    sa.ForeignKeyConstraint(['import_file_id'], ['import_files.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_nf_emitida_matching', 'notas_fiscais_emitidas', ['nota_fiscal', 'bank_account_id'], unique=False)
    op.create_index(op.f('ix_notas_fiscais_emitidas_nota_fiscal'), 'notas_fiscais_emitidas', ['nota_fiscal'], unique=False)
    op.add_column('bank_transactions', sa.Column('due_date', sa.Date(), nullable=True))
    op.add_column('bank_transactions', sa.Column('agency', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bank_transactions', 'agency')
    op.drop_column('bank_transactions', 'due_date')
    op.drop_index(op.f('ix_notas_fiscais_emitidas_nota_fiscal'), table_name='notas_fiscais_emitidas')
    op.drop_index('ix_nf_emitida_matching', table_name='notas_fiscais_emitidas')
    op.drop_table('notas_fiscais_emitidas')
    # ### end Alembic commands ###
