"""vincula documento recebido ao match de conciliacao

Revision ID: a3899b42f342
Revises: 6b34f48a4afe
Create Date: 2026-09-12 16:07:04.374535

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3899b42f342'
down_revision: Union[str, Sequence[str], None] = '6b34f48a4afe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reconciliation_matches', sa.Column('documento_recebido_id', sa.Uuid(), nullable=True))
    with op.batch_alter_table('reconciliation_matches') as batch_op:
        batch_op.create_foreign_key(
            'fk_reconciliation_matches_documento_recebido_id', 'documentos_recebidos',
            ['documento_recebido_id'], ['id'],
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reconciliation_matches') as batch_op:
        batch_op.drop_constraint('fk_reconciliation_matches_documento_recebido_id', type_='foreignkey')
    op.drop_column('reconciliation_matches', 'documento_recebido_id')
    # ### end Alembic commands ###
