"""schema inicial

Revision ID: c258a15af342
Revises: 
Create Date: 2026-09-11 20:59:25.233984

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c258a15af342'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('action', sa.Enum('IMPORTACAO', 'CONCILIACAO', 'ALTERACAO', 'AJUSTE_MANUAL', 'IGNORADO', 'REABERTURA', 'EXPORTACAO', 'EXCLUSAO', 'FECHAMENTO', name='audit_action'), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=True),
    sa.Column('performed_by', sa.String(length=255), nullable=False),
    sa.Column('performed_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('before', sa.JSON(), nullable=True),
    sa.Column('after', sa.JSON(), nullable=True),
    sa.Column('context', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('clients',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('bank_accounts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('client_id', sa.Uuid(), nullable=False),
    sa.Column('bank', sa.String(length=100), nullable=False),
    sa.Column('agency', sa.String(length=20), nullable=True),
    sa.Column('account_number', sa.String(length=30), nullable=False),
    sa.Column('date_tolerance_business_days', sa.SmallInteger(), nullable=False),
    sa.Column('amount_tolerance', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('consider_interest', sa.Boolean(), nullable=False),
    sa.Column('consider_fee_in_settlement', sa.Boolean(), nullable=False),
    sa.Column('period_cutoff_enabled', sa.Boolean(), nullable=False),
    sa.Column('separate_anticipations', sa.Boolean(), nullable=False),
    sa.Column('grouping_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('import_files',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('bank_account_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.Enum('ERP', 'BANK', name='import_file_kind'), nullable=False),
    sa.Column('original_filename', sa.String(length=500), nullable=False),
    sa.Column('file_hash', sa.String(length=64), nullable=False),
    sa.Column('storage_path', sa.String(length=1000), nullable=False),
    sa.Column('competencia_year', sa.Integer(), nullable=False),
    sa.Column('competencia_month', sa.Integer(), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=True),
    sa.Column('period_end', sa.Date(), nullable=True),
    sa.Column('row_count', sa.Integer(), nullable=True),
    sa.Column('imported_by', sa.String(length=255), nullable=True),
    sa.Column('imported_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['bank_account_id'], ['bank_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_import_files_file_hash'), 'import_files', ['file_hash'], unique=False)
    op.create_table('bank_transactions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('import_file_id', sa.Uuid(), nullable=False),
    sa.Column('bank_account_id', sa.Uuid(), nullable=False),
    sa.Column('bank', sa.String(length=100), nullable=False),
    sa.Column('movement_date', sa.Date(), nullable=False),
    sa.Column('nosso_numero', sa.String(length=50), nullable=False),
    sa.Column('seu_numero', sa.String(length=50), nullable=True),
    sa.Column('normalized_title', sa.String(length=50), nullable=True),
    sa.Column('payer_name', sa.String(length=255), nullable=True),
    sa.Column('operation_type', sa.String(length=100), nullable=True),
    sa.Column('principal_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('fee_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('interest_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('final_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('source_sheet', sa.String(length=50), nullable=True),
    sa.Column('raw_data', sa.JSON(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['bank_account_id'], ['bank_accounts.id'], ),
    sa.ForeignKeyConstraint(['import_file_id'], ['import_files.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bank_transactions_normalized_title'), 'bank_transactions', ['normalized_title'], unique=False)
    op.create_index('ix_bank_tx_matching', 'bank_transactions', ['normalized_title', 'movement_date', 'bank_account_id'], unique=False)
    op.create_table('erp_transactions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('import_file_id', sa.Uuid(), nullable=False),
    sa.Column('bank_account_id', sa.Uuid(), nullable=False),
    sa.Column('account_local', sa.String(length=100), nullable=True),
    sa.Column('transaction_date', sa.Date(), nullable=False),
    sa.Column('invoice_number_raw', sa.String(length=50), nullable=True),
    sa.Column('normalized_title', sa.String(length=50), nullable=True),
    sa.Column('tipo', sa.String(length=50), nullable=True),
    sa.Column('tipo_documento', sa.String(length=100), nullable=True),
    sa.Column('nota_fiscal', sa.String(length=50), nullable=True),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('incoming_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('outgoing_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('balance', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('is_anticipation', sa.Boolean(), nullable=False),
    sa.Column('raw_data', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['bank_account_id'], ['bank_accounts.id'], ),
    sa.ForeignKeyConstraint(['import_file_id'], ['import_files.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_erp_transactions_normalized_title'), 'erp_transactions', ['normalized_title'], unique=False)
    op.create_index('ix_erp_tx_matching', 'erp_transactions', ['normalized_title', 'transaction_date', 'bank_account_id'], unique=False)
    op.create_table('reconciliations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('bank_account_id', sa.Uuid(), nullable=False),
    sa.Column('competencia_year', sa.Integer(), nullable=False),
    sa.Column('competencia_month', sa.SmallInteger(), nullable=False),
    sa.Column('status', sa.Enum('RASCUNHO', 'EM_ANALISE', 'CONCILIADA', 'FECHADA', 'REABERTA', name='reconciliationlifecyclestatus'), nullable=False),
    sa.Column('erp_import_file_id', sa.Uuid(), nullable=True),
    sa.Column('bank_import_file_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_by', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['bank_account_id'], ['bank_accounts.id'], ),
    sa.ForeignKeyConstraint(['bank_import_file_id'], ['import_files.id'], ),
    sa.ForeignKeyConstraint(['erp_import_file_id'], ['import_files.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reconciliation_matches',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('reconciliation_id', sa.Uuid(), nullable=False),
    sa.Column('bank_transaction_id', sa.Uuid(), nullable=True),
    sa.Column('erp_transaction_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.String(length=60), nullable=False),
    sa.Column('confidence', sa.SmallInteger(), nullable=False),
    sa.Column('diagnostic', sa.Text(), nullable=True),
    sa.Column('is_manual_override', sa.Boolean(), nullable=False),
    sa.Column('ignored', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['bank_transaction_id'], ['bank_transactions.id'], ),
    sa.ForeignKeyConstraint(['erp_transaction_id'], ['erp_transactions.id'], ),
    sa.ForeignKeyConstraint(['reconciliation_id'], ['reconciliations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reconciliation_matches_status'), 'reconciliation_matches', ['status'], unique=False)
    op.create_table('manual_adjustments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('reconciliation_match_id', sa.Uuid(), nullable=False),
    sa.Column('reason', sa.Enum('NUMERACAO_DIFERENTE', 'DIFERENCA_DE_DATA', 'AGRUPAMENTO', 'AJUSTE_CONTABIL', 'CLASSIFICACAO', 'OUTRO', name='manual_adjustment_reason'), nullable=False),
    sa.Column('observation', sa.Text(), nullable=True),
    sa.Column('previous_status', sa.String(length=60), nullable=False),
    sa.Column('new_status', sa.String(length=60), nullable=False),
    sa.Column('performed_by', sa.String(length=255), nullable=False),
    sa.Column('performed_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['reconciliation_match_id'], ['reconciliation_matches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('manual_adjustments')
    op.drop_index(op.f('ix_reconciliation_matches_status'), table_name='reconciliation_matches')
    op.drop_table('reconciliation_matches')
    op.drop_table('reconciliations')
    op.drop_index('ix_erp_tx_matching', table_name='erp_transactions')
    op.drop_index(op.f('ix_erp_transactions_normalized_title'), table_name='erp_transactions')
    op.drop_table('erp_transactions')
    op.drop_index('ix_bank_tx_matching', table_name='bank_transactions')
    op.drop_index(op.f('ix_bank_transactions_normalized_title'), table_name='bank_transactions')
    op.drop_table('bank_transactions')
    op.drop_index(op.f('ix_import_files_file_hash'), table_name='import_files')
    op.drop_table('import_files')
    op.drop_table('bank_accounts')
    op.drop_table('clients')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
